Bash Prompt: Add custom bash prompt.

diff --git a/.bash/prompt b/.bash/prompt
--- a/.bash/prompt
+++ b/.bash/prompt
@@ -39,9 +39,71 @@ bakwht='\e[47m'   # White
 
 txtrst='\e[0m'    # Text Reset
 
-# print_before_prompt () {
-#   # printf "\n[$txtred $USER $txtrst] [$undgrn $PWD $txtrst]\n"
-# }
-# PROMPT_COMMAND=print_before_prompt 
-# PS1="\n[ \h : \u ] [ \W ]\n🔥🇹🇹💻🔥>"
-# PS1="\n🔥 🇹🇹 🔥 > "
+#############################################
+# get exit status of previous command
+#############################################
+function nonzero_return() {
+	RETVAL=$?
+	
+  echo "[exit: $RETVAL]"
+}
+
+
+#############################################
+# get current branch in git repo
+#############################################
+
+function parse_git_branch() {
+	BRANCH=`git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
+	if [ ! "${BRANCH}" == "" ]
+	then
+		STAT=`parse_git_dirty`
+		echo "[git: ${BRANCH}${STAT}]"
+	else
+		echo ""
+	fi
+}
+
+#############################################
+# get current status of git repo
+#############################################
+
+function parse_git_dirty {
+	status=`git status 2>&1 | tee`
+	dirty=`echo -n "${status}" 2> /dev/null | grep "modified:" &> /dev/null; echo "$?"`
+	untracked=`echo -n "${status}" 2> /dev/null | grep "Untracked files" &> /dev/null; echo "$?"`
+	ahead=`echo -n "${status}" 2> /dev/null | grep "Your branch is ahead of" &> /dev/null; echo "$?"`
+	newfile=`echo -n "${status}" 2> /dev/null | grep "new file:" &> /dev/null; echo "$?"`
+	renamed=`echo -n "${status}" 2> /dev/null | grep "renamed:" &> /dev/null; echo "$?"`
+	deleted=`echo -n "${status}" 2> /dev/null | grep "deleted:" &> /dev/null; echo "$?"`
+	bits=''
+	if [ "${renamed}" == "0" ]; then
+		bits=">${bits}"
+	fi
+	if [ "${ahead}" == "0" ]; then
+		bits="*${bits}"
+	fi
+	if [ "${newfile}" == "0" ]; then
+		bits="+${bits}"
+	fi
+	if [ "${untracked}" == "0" ]; then
+		bits="?${bits}"
+	fi
+	if [ "${deleted}" == "0" ]; then
+		bits="x${bits}"
+	fi
+	if [ "${dirty}" == "0" ]; then
+		bits="!${bits}"
+	fi
+	if [ ! "${bits}" == "" ]; then
+		echo " ${bits}"
+	else
+		echo ""
+	fi
+}
+
+
+#############################################
+# PS1 Prompt
+#############################################
+export PS1="\n\\$ \u 🔥 🇹🇹  💻 🔥 : \h @ \w \`parse_git_branch\` \`nonzero_return\` \n>"
